#!/bin/bash

# Directory where the wav files are located. Modify this if needed.
SOUND_DIR="./sound/vox/"
ALT_SOUND_DIR="./sound/fvox/"

# Process options and arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -f)
            SOUND_DIR=$ALT_SOUND_DIR
            shift
            ;;
        *)
            break # Exit the loop if we encounter a word or another option
            ;;
    esac
done

for word in "$@"; do
    sound_file="${SOUND_DIR}/${word}.wav"
    if [[ -f $sound_file ]]; then
        afplay "$sound_file"
    else
        echo "Warning: Sound file for '${word}' not found."
    fi
done

for word in "$@"; do
    sound_file="${SOUND_DIR}/${word}.wav"
    if [[ -f $sound_file ]]; then
        case $PLATFORM in
            Darwin)   # macOS
                afplay "$sound_file"
                ;;
            Linux)
                aplay "$sound_file"
                ;;
        esac
    else
        echo "Warning: Sound file for '${word}' not found."
    fi
done
